name: Selenium SortShellTest

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: npm install

    - name: Instalar Chrome y ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        # crear enlace solo si no existe
        [ -e /usr/bin/chromedriver ] || sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Ejecutar sortShellTest en headless
      run: npm run sort-test
      env:
        CI: true